// <auto-generated />
using System;
using MgpTechTickets.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MgpTechTickets.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("MgpTechTickets.Models.Agenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AmbienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("MgpTechTickets.Models.Ambiente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cnpj")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("TEXT");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ambientes");
                });

            modelBuilder.Entity("MgpTechTickets.Models.CanaisComunicacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AmbienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status_")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.ToTable("Canais");
                });

            modelBuilder.Entity("MgpTechTickets.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AmbienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status_")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("MgpTechTickets.Models.Chamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AmbienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFechamento")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FilialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Protocolo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SetorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status_")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserFinishId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserRedirectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.HasIndex("FilialId");

                    b.HasIndex("SetorId");

                    b.HasIndex("UserFinishId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserRedirectId");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("MgpTechTickets.Models.ChamadoLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AmbienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChamadoFilhoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAlterado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Solucao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status_")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ChamadoFilhoId");

                    b.HasIndex("UserId");

                    b.ToTable("ChamadoLogs");
                });

            modelBuilder.Entity("MgpTechTickets.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AmbienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CliNome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("MgpTechTickets.Models.Filial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AmbienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilCnpj")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilNomefant")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilRazsoc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilStatus")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.ToTable("Filiais");
                });

            modelBuilder.Entity("MgpTechTickets.Models.FilialDados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CpfRepre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailFinan")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FilialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdentiRepre")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeFinan")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeRepre")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeleFinan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilialId");

                    b.ToTable("FilialDados");
                });

            modelBuilder.Entity("MgpTechTickets.Models.FilialEndereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bairro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cep")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Complemento")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FilialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Logradouro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilialId");

                    b.ToTable("FilialEnderecos");
                });

            modelBuilder.Entity("MgpTechTickets.Models.Pendencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AmbienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CanalId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChamadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFechamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Imagem")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendenciaImagem")
                        .HasColumnType("TEXT");

                    b.Property<string>("Solucao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubCategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserFinishId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.HasIndex("CanalId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ChamadoId");

                    b.HasIndex("SubCategoriaId");

                    b.HasIndex("UserFinishId");

                    b.HasIndex("UserId");

                    b.ToTable("Pendencias");
                });

            modelBuilder.Entity("MgpTechTickets.Models.PendenciaImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AmbienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChamadoFilhoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PathName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.HasIndex("ChamadoFilhoId");

                    b.ToTable("PendenciaImages");
                });

            modelBuilder.Entity("MgpTechTickets.Models.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AmbienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MgpTechTickets.Models.Setores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AmbienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status_")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tempo")
                        .HasColumnType("TEXT");

                    b.Property<string>("TempoMedio")
                        .HasColumnType("TEXT");

                    b.Property<string>("TempoRapido")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.ToTable("Setores");
                });

            modelBuilder.Entity("MgpTechTickets.Models.SubCategorias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AmbienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status_")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AmbienteId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("SubCategorias");
                });

            modelBuilder.Entity("MgpTechTickets.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MgpTechTickets.Models.Agenda", b =>
                {
                    b.HasOne("MgpTechTickets.Models.Ambiente", "Ambiente")
                        .WithMany()
                        .HasForeignKey("AmbienteId");
                });

            modelBuilder.Entity("MgpTechTickets.Models.CanaisComunicacao", b =>
                {
                    b.HasOne("MgpTechTickets.Models.Ambiente", "Ambiente")
                        .WithMany()
                        .HasForeignKey("AmbienteId");
                });

            modelBuilder.Entity("MgpTechTickets.Models.Categoria", b =>
                {
                    b.HasOne("MgpTechTickets.Models.Ambiente", "Ambiente")
                        .WithMany()
                        .HasForeignKey("AmbienteId");
                });

            modelBuilder.Entity("MgpTechTickets.Models.Chamado", b =>
                {
                    b.HasOne("MgpTechTickets.Models.Ambiente", "Ambiente")
                        .WithMany()
                        .HasForeignKey("AmbienteId");

                    b.HasOne("MgpTechTickets.Models.Filial", "Filial")
                        .WithMany()
                        .HasForeignKey("FilialId");

                    b.HasOne("MgpTechTickets.Models.Setores", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId");

                    b.HasOne("MgpTechTickets.Models.Users", "UserFinish")
                        .WithMany()
                        .HasForeignKey("UserFinishId");

                    b.HasOne("MgpTechTickets.Models.Users", "User")
                        .WithMany("Chamados")
                        .HasForeignKey("UserId");

                    b.HasOne("MgpTechTickets.Models.Users", "UserRedirect")
                        .WithMany()
                        .HasForeignKey("UserRedirectId");
                });

            modelBuilder.Entity("MgpTechTickets.Models.ChamadoLog", b =>
                {
                    b.HasOne("MgpTechTickets.Models.Ambiente", "Ambiente")
                        .WithMany()
                        .HasForeignKey("AmbienteId");

                    b.HasOne("MgpTechTickets.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("MgpTechTickets.Models.Chamado", "ChamadoFilho")
                        .WithMany()
                        .HasForeignKey("ChamadoFilhoId");

                    b.HasOne("MgpTechTickets.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("MgpTechTickets.Models.Cliente", b =>
                {
                    b.HasOne("MgpTechTickets.Models.Ambiente", "Ambiente")
                        .WithMany()
                        .HasForeignKey("AmbienteId");
                });

            modelBuilder.Entity("MgpTechTickets.Models.Filial", b =>
                {
                    b.HasOne("MgpTechTickets.Models.Ambiente", "Ambiente")
                        .WithMany()
                        .HasForeignKey("AmbienteId");
                });

            modelBuilder.Entity("MgpTechTickets.Models.FilialDados", b =>
                {
                    b.HasOne("MgpTechTickets.Models.Filial", "Filial")
                        .WithMany()
                        .HasForeignKey("FilialId");
                });

            modelBuilder.Entity("MgpTechTickets.Models.FilialEndereco", b =>
                {
                    b.HasOne("MgpTechTickets.Models.Filial", "Filial")
                        .WithMany()
                        .HasForeignKey("FilialId");
                });

            modelBuilder.Entity("MgpTechTickets.Models.Pendencia", b =>
                {
                    b.HasOne("MgpTechTickets.Models.Ambiente", "Ambiente")
                        .WithMany()
                        .HasForeignKey("AmbienteId");

                    b.HasOne("MgpTechTickets.Models.CanaisComunicacao", "Canal")
                        .WithMany()
                        .HasForeignKey("CanalId");

                    b.HasOne("MgpTechTickets.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("MgpTechTickets.Models.Chamado", "Chamado")
                        .WithMany("Pendencias")
                        .HasForeignKey("ChamadoId");

                    b.HasOne("MgpTechTickets.Models.SubCategorias", "SubCategoria")
                        .WithMany()
                        .HasForeignKey("SubCategoriaId");

                    b.HasOne("MgpTechTickets.Models.Users", "UserFinish")
                        .WithMany()
                        .HasForeignKey("UserFinishId");

                    b.HasOne("MgpTechTickets.Models.Users", "User")
                        .WithMany("Pendencias")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("MgpTechTickets.Models.PendenciaImage", b =>
                {
                    b.HasOne("MgpTechTickets.Models.Ambiente", "Ambiente")
                        .WithMany()
                        .HasForeignKey("AmbienteId");

                    b.HasOne("MgpTechTickets.Models.Pendencia", "ChamadoFilho")
                        .WithMany()
                        .HasForeignKey("ChamadoFilhoId");
                });

            modelBuilder.Entity("MgpTechTickets.Models.Roles", b =>
                {
                    b.HasOne("MgpTechTickets.Models.Ambiente", "Ambiente")
                        .WithMany()
                        .HasForeignKey("AmbienteId");
                });

            modelBuilder.Entity("MgpTechTickets.Models.Setores", b =>
                {
                    b.HasOne("MgpTechTickets.Models.Ambiente", "Ambiente")
                        .WithMany()
                        .HasForeignKey("AmbienteId");
                });

            modelBuilder.Entity("MgpTechTickets.Models.SubCategorias", b =>
                {
                    b.HasOne("MgpTechTickets.Models.Ambiente", "Ambiente")
                        .WithMany()
                        .HasForeignKey("AmbienteId");

                    b.HasOne("MgpTechTickets.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");
                });

            modelBuilder.Entity("MgpTechTickets.Models.Users", b =>
                {
                    b.HasOne("MgpTechTickets.Models.Roles", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");
                });
#pragma warning restore 612, 618
        }
    }
}
